
## ⚙️ **Basic Steps to Build a Neural Network (Using iris.csv)**

---

### **1️⃣ Import Libraries**


In [2]:

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import numpy as np

---

### **2️⃣ Prepare the Data**

We assume the CSV file looks like this (standard Iris format):

| sepal_length | sepal_width | petal_length | petal_width | species    |
| ------------ | ----------- | ------------ | ----------- | ---------- |
| 5.1          | 3.5         | 1.4          | 0.2         | setosa     |
| 7.0          | 3.2         | 4.7          | 1.4         | versicolor |
| 6.3          | 3.3         | 6.0          | 2.5         | virginica  |

📁 **File name:** `iris.csv`

Now, load and preprocess it:

In [3]:
# Load CSV file
df = pd.read_csv('../Data/iris.csv')
print(df.shape)
df.head()

(150, 6)


Id  Sepal Length (cm)  Sepal Width (cm)  Petal Length (cm)  \
0   1                5.1               3.5                1.4   
1   2                4.9               3.0                1.4   
2   3                4.7               3.2                1.3   
3   4                4.6               3.1                1.5   
4   5                5.0               3.6                1.4   

   Petal Width (cm)      Species  
0               0.2  Iris-setosa  
1               0.2  Iris-setosa  
2               0.2  Iris-setosa  
3               0.2  Iris-setosa  
4               0.2  Iris-setosa

In [4]:

# Separate features and labels
# X = df.iloc[:, 1:-1].values  # all columns except the first and the last
# y = df.iloc[:, -1].values  # last column (species)

# Split features (X) and target (y)
X = df.drop(['Id', 'Species'], axis=1)
y = df['Species']
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

* `LabelEncoder` is a class from `sklearn.preprocessing` that converts categorical labels (text) into numeric codes.

In [5]:

# Encode text labels (setosa, versicolor, virginica → 0,1,2)
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

y_encoded

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [25]:

# One-hot encode target
y_onehot = tf.keras.utils.to_categorical(y_encoded)
y_onehot


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [26]:
# Scale the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split into train/test sets
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_onehot, test_size=0.2, random_state=42
)

---
### **3️⃣ Build the Model**

A
small
dense
network
for 3 -class classification:


In [31]:
model = keras.Sequential([
    keras.Input(shape=[4]),
    layers.Dense(8, activation='relu'),
    layers.Dense(3, activation='softmax')
])
# model.weights

---
### **4️⃣ Compile the Model**


In [59]:
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.01),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)
# For **multi-class classification** → use **Categorical Cross-Entropy** (with softmax)

---
### **5️⃣ Train the Model**


In [63]:
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True)

history = model.fit(
    X_train, y_train,
    epochs=50,
    batch_size=8,
    validation_split=0.2,
    callbacks=[early_stop],
    verbose=2
)

# print("Final training loss:", history.history['loss'][-1])
# print("Final validation loss:", history.history['val_loss'][-1])
# print("Final training accuracy:", history.history['accuracy'][-1])
# print("Final validation accuracy:", history.history['val_accuracy'][-1])

Epoch 1/50
12/12 - 0s - 14ms/step - accuracy: 0.9792 - loss: 0.0485 - val_accuracy: 0.9583 - val_loss: 0.1685
Epoch 2/50
12/12 - 0s - 12ms/step - accuracy: 0.9792 - loss: 0.0465 - val_accuracy: 0.9583 - val_loss: 0.1769
Epoch 3/50
12/12 - 0s - 11ms/step - accuracy: 0.9792 - loss: 0.0477 - val_accuracy: 0.9583 - val_loss: 0.1772


---
### **6️⃣ Evaluate & Make Predictions**


In [64]:
# Evaluate
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"\n✅ Test Accuracy: {test_acc:.3f}")

# Predict
predictions = model.predict(X_test)
print(predictions[:5])
predicted_classes = np.argmax(predictions, axis=1)
actual_classes = np.argmax(y_test, axis=1)

print("\nPredicted Classes:", predicted_classes[:10])
print("Actual Classes:   ", actual_classes[:10])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 249ms/step - accuracy: 1.0000 - loss: 0.0313

✅ Test Accuracy: 1.000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
[[4.5683166e-05 9.9913377e-01 8.2058791e-04]
 [9.9985480e-01 1.4512712e-04 3.4858847e-15]
 [4.7190731e-16 4.6612245e-11 1.0000000e+00]
 [7.3835625e-05 9.9216193e-01 7.7642608e-03]
 [1.8530105e-06 9.9409616e-01 5.9019839e-03]]

Predicted Classes: [1 0 2 1 1 0 1 2 1 1]
Actual Classes:    [1 0 2 1 1 0 1 2 1 1]


---
### ✅ **Expected Output**

```
Epoch
50 / 50
...
✅ Test
Accuracy: 0.966

Predicted
Classes: [0 1 2 1 0 2 2 1 0 1]
Actual
Classes: [0 1 2 1 0 2 2 1 0 1]
```

---

### visualize :(learning curve)

* you can visualize how the model learns over epochs a **plot of the training vs validation accuracy / loss** (learning curve)
